language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - ng build

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend remirosa92/udagram-frontend:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push remirosa92/udagram-frontend